// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_2.Model;

#nullable disable

namespace project_2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260114102503_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("project_2.Model.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Dob")
                        .HasColumnType("date");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dob = new DateTime(1955, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = true,
                            Name = "Nguyễn Nhật Ánh"
                        },
                        new
                        {
                            Id = 2,
                            Dob = new DateTime(1920, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = true,
                            Name = "Tô Hoài"
                        },
                        new
                        {
                            Id = 3,
                            Dob = new DateTime(1915, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = true,
                            Name = "Nam Cao"
                        });
                });

            modelBuilder.Entity("project_2.Model.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tiểu thuyết tình cảm",
                            Title = "Mắt Biếc",
                            Year = 1990
                        },
                        new
                        {
                            Id = 2,
                            Description = "Truyện thiếu nhi",
                            Title = "Dế Mèn Phiêu Lưu Ký",
                            Year = 1941
                        },
                        new
                        {
                            Id = 3,
                            Description = "Truyện ngắn",
                            Title = "Chí Phèo",
                            Year = 1941
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tiểu thuyết",
                            Title = "Tôi Thấy Hoa Vàng Trên Cỏ Xanh",
                            Year = 2010
                        });
                });

            modelBuilder.Entity("project_2.Model.Book_Authors", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 3
                        });
                });

            modelBuilder.Entity("project_2.Model.Book_Authors", b =>
                {
                    b.HasOne("project_2.Model.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project_2.Model.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("project_2.Model.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("project_2.Model.Book", b =>
                {
                    b.Navigation("BookAuthors");
                });
#pragma warning restore 612, 618
        }
    }
}
